### ISSUE TITLE
avg模式下对话的进行

### ISSUE THREAD

**Issue by Arcadia822** [EOF-game/EOF-game.github.io#1]
必须在对话框内点击才能触发，并且只有在上一次的点击在对话框内时，才能使用回车键触发

版本：1.02
系统：win7

**Comment by jim-kirisame** [comment]
这是一个已知BUG，我去问问能不能修

**Comment by jim-kirisame** [comment]
程序员工作结束了，这个不算BUG的功能改进应该是不会修的了。
